services:
  app:
    image: ghcr.io/shba007/nuxtemplate:latest@sha256:6262b8b70a4367be2b9dcaaa83d4da0dd130e0019e7bae12a7c39173882d5782
    env_file:
      - .env
    volumes:
      - nuxtemplate_data:/app/.data
    expose:
      - 3000
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  nuxtemplate_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/nuxtemplate/.data

networks:
  internal:
    driver: overlay
