services:
  app:
    image: ghcr.io/shba007/nuxtemplate:latest@sha256:a3af778125cdee0681d4f35e855bd834b0c1e26080dc75775ffb740bb8b9e245
    env_file:
      - .env
    volumes:
      - nuxtemplate_data:/app/.data
    expose:
      - 3000
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  nuxtemplate_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/nuxtemplate/.data

networks:
  internal:
    driver: overlay
