version: '3.9'
services:
  app:
    image: ghcr.io/shba007/nuxtemplate:latest
    env_file:
      - .env.prod
    ports:
      - 4000:3000
    networks:
      - front-tier
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  front-tier:
    driver: overlay
