name: Nuxt CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Corepack for pnpm
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      # - name: Run Tests
      # run: pnpm test

      # - name: Lint Code
      #   run: pnpm linit

      # - name: Format Code
      #   run: pnpm format

      - name: Bulid Artifacts
        run: pnpm build

      - name: Create Version and Changelog
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          pnpx changelogen@latest --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: release new version'
          title: 'chore: release new version'
          body: |
            This PR contains:
            - Version Bump
            - Updated CHANGELOG.md
            - Formatted and linted code
          branch: release/next-version
          base: develop
          labels: release
