name: Nuxt CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        run: npm i -g pnpm

      - name: Setup Node.js with pnpm
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build Artifacts
        run: pnpm build

      # - name: Run Tests
      #   run: pnpm test

      - name: Lint Code
        run: pnpm lint || echo "Linting failed, but continuing"

      - name: Format Code
        run: pnpm format

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpx semantic-release
