name: Nuxt CI

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

on:
  push:
    branches:
      - develop

jobs:
  build:
    if: '!contains(github.event.head_commit.message, "[skip ci]")'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Setup Node.js with pnpm
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build Artifacts
        run: pnpm build

      # - name: Run Tests
      #   run: pnpm test

      - name: Lint Code
        run: pnpm lint || echo "Linting failed, but continuing"

      - name: Format Code
        run: pnpm format

      - name: AutoFix Code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: apply code fixes [skip ci]'

      - name: Bump Version
        id: bump
        run: |
          VERSION_OUTPUT=$(pnpx changelogen@latest --bump)
          echo "version=$VERSION_OUTPUT" >> $GITHUB_OUTPUT

      - name: Create or Update Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'chore(release): update version'
          title: 'chore(release): update version'
          body: '${{ steps.bump.outputs.version }}'
          branch: 'release/update-version'
          base: 'develop'
          delete-branch: true
