name: Nuxt Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Corepack for pnpm
        run: corepack enable

      - name: Setup Node.js with Corepack
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Lint Code
        run: pnpm lint || echo "Linting failed, but continuing"

      - name: Format Code
        run: pnpm format

      - name: Create Release Pull Request
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
