name: Nuxt Release

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release:
    if: contains(github.event.head_commit.message, 'chore(release)')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Setup Node.js with pnpm
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Create Release Note
        run: |
          pnpx changelogen@latest gh release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
